### ISSUE TITLE
Corrección en el código

### ISSUE THREAD

**Issue by acss1881** [manishjanky/ngx-sortable#14]
Al insertar un texto a la lista me colocar el primer index en undefined ajustar código para evitar este error. 

 NgxSortableComponent.prototype.handleDrop = function (droppedIndex) {
       
        var item = this.items[this.draggedIndex];
        if (item === undefined) { return false;} // "see" codigo temporal evita ordenar lista con  undefined -1
        this.items.splice(this.draggedIndex, 1);
        this.items.splice(droppedIndex, 0, item);
        this.draggedIndex = -1;
        this.onDragOverIndex = -1;
        this.listSorted.emit(this.items);
    };

**Comment by manishjanky** [comment]
Hey @acss1881  sorry for the delayed response, can you please elaborate I did not get what is the problem you are facing.
