### ISSUE TITLE
How to disable the sorting or drag and drob functionality.

### ISSUE THREAD

**Issue by prem-k** [manishjanky/ngx-sortable#16]
How to disable the sorting or drag and drob functionality. Please reply it's urgent.

Please  add a new @input decorator for manage draggable "true/false" value in UL LI. 
Like : 
<li draggable="true" (click)="selectItem(item)" >

**Comment by manishjanky** [comment]
@prem-k  the component was created solely for sorting using drag and drop so there is no option to disable that as of now. still will see what I can do.
Closing this for now
