### ISSUE TITLE
Drag&drop glitches when dragging under a last item

### ISSUE THREAD

**Issue by brano-p** [manishjanky/ngx-sortable#19]
The following behaviour is reproducible on the demo implementation (at https://manishjanky.github.io/ngx-sortable/), too (not just in my environment):
![image](https://user-images.githubusercontent.com/24959416/86342301-b26ebd80-bc57-11ea-8984-9a21aa680ddd.png)
Let's say I'm going to drag Amie under Goldie. The lowest position you can drag (drop target) to is OVER Goldie:
![image](https://user-images.githubusercontent.com/24959416/86342878-7e47cc80-bc58-11ea-87be-22c694eb5618.png)
The drop target element stays there and does not disappear as expected.

**Comment by kunalPatel1428** [comment]
Any update on this issue?

**Comment by sheshank407** [comment]
Facing Same Issue

**Comment by manishjanky** [comment]
Sorry for the delayed response.
Looking into this.

**Comment by manishjanky** [comment]
Please update to `v2.0.0`
