### ISSUE TITLE
Item can be dragged under itself, and after dropping will appear after the next item, instead of before it.

### ISSUE THREAD

**Issue by eikonos** [manishjanky/ngx-sortable#33]
This bug is reproducible in the demo.
1. pick up the third item ("Amie Franklin") in the list
2. at first the drop target will be above "Amie Franklin" in the list
3. drag the floating placeholder down just a little until it is under "Amie Franklin", but above the fourth item
4. drop the floating placeholder
5. the list will resort and "Amie Franklin" will appear in the fourth position, and the item which was below the drop target will be third

Expected behaviour:
- when a list item is dropped above or below itself, it should remain at the same position

**Comment by GaganJatana** [comment]
i incountered the  same issue any fix ??

**Comment by eikonos** [comment]
For me, the fix was to switch to dragula instead.
