### ISSUE TITLE
 Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [manishjanky/ngx-sortable#35]
I just installed the plugin and added in app.module.ts and nothing else. I am getting this error ` Cannot read property 'id' of undefined at registerNgModuleType (core.js:35936)`

<img width="653" alt="Screenshot 2020-10-13 at 12 31 58 PM" src="https://user-images.githubusercontent.com/9896335/95826620-330d8180-0d50-11eb-8d3b-718cca81f8da.png">

Versions are as below

    "ngx-sortable": "^1.0.3",

    "@angular/animations": "^9.0.6",
    "@angular/cdk": "^9.1.3",
    "@angular/common": "^9.0.6",
    "@angular/compiler": "^9.0.6",
    "@angular/core": "^9.0.6",
    "@angular/forms": "^9.0.6",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "^9.0.6",
    "@angular/platform-browser-dynamic": "^9.0.6",
    "@angular/router": "^9.0.6",

**Comment by YonathanMeguira** [comment]
@rajeshwarpatlolla did you manage to solve it ? I'm fighting with this.

**Comment by manishjanky** [comment]
This problem does not seem to be related with this component.
