### ISSUE TITLE
error NG6002

### ISSUE THREAD

**Issue by robertnicjoo** [manishjanky/ngx-sortable#37]
### `1` When I add this package to my sharedModules file I get this error

```
 ERROR in node_modules/ngx-sortable/dist/ngx-sortable.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of SharedModule, but could not be resolved to an NgModule class.

    This likely means that the library (ngx-sortable) which declares NgxSortableModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

### `2`  **Also I want to know is it possible I use my own design instead of default list design?**

Something like this:

![Screenshot(5)](https://user-images.githubusercontent.com/8672823/100062668-8c45f600-2e62-11eb-8df7-94c43505d598.png)

**Comment by manishjanky** [comment]
Sorry for the delayed response. I believe its because of the way it was imported, if you can show me how the setup is on your end I may be able to help.

**Comment by robertnicjoo** [comment]
> Sorry for the delayed response.

Dude, this issue belongs to **2 years ago**!

**Comment by manishjanky** [comment]
@robertnicjoo yeah I know, just could not concentrate on this plugin due to some unavoidable reasons.

> > Sorry for the delayed response.
> 
> Dude, this issue belongs to **2 years ago**!

@robertnicjoo yeah I know, just could not concentrate on this plugin due to some unavoidable reasons.

**Comment by robertnicjoo** [comment]
Dont worry about it. It's already long finished and I don't remember it anymore 😊
