### ISSUE TITLE
Unable to find index inside ngx-sortable component... Every time it is throwing 0 as index value

### ISSUE THREAD

**Issue by Shiva4393** [manishjanky/ngx-sortable#5]
Please Provide any suggestion for getting index inside ngx-sortable component

**Comment by pranavcbalan** [comment]
The easiest way is to use Array#indexOf() method, but it's not an efficient way.

`{{items.indexOf(item)}}`

**Comment by manishjanky** [comment]
First of all sorry for the delayed response.
But can you please elaborate what you are trying to achieve. What index you want?

**Comment by noonesstudios** [comment]
Joining the request
An accessor for the list item's index
Currently it is only possible to access the item itself but not its position generated by `ngFor`
```
*ngFor=let item of items; let i = index
div > {{i + 1}} {{item.name}}
```

**Comment by manishjanky** [comment]
Please update to `v2.0.0`
