### ISSUE TITLE
not work in safari mobile

### ISSUE THREAD

**Issue by hkkhchan** [manishjanky/ngx-sortable#6]
not work in safari mobile.

**Comment by hkkhchan** [comment]
> Sorry for the delayed response. Let me have a look will update you soon.

fyi, finally, I use this library instead.
[https://github.com/timruffles/mobile-drag-drop](url)

but I still face a problem that this library not deal with desktop device.
When the environment is desktop device, It will use the native drag instead. 
Then It is unable to detect the position of mouse when on (dragstart) or (drag) with REAL TIME.

**Comment by manishjanky** [comment]
@hkkhchan Sorry, due to some unavoidable reason I could not concentrate on this component. Trying to clear out the backlog now.
